---
- name: nxos module
  hosts: nxos
  gather_facts: no
  vars:
    ssh:
      host: "{{ ansible_host }}"
      username: admin
      password: Night$hade900
      transport: cli

      tasks:
         nxos_user:
           provider: "{{ ssh }}"
           name: ansible
           state: absent
           roles: network-admin
           configured_password: ansible
           update_password: on_create
