---
- name: nxos module
  hosts: all
  gather_facts: falce
  connection: local

  vars:
    ssh:
      host: "{{ ansible_host }}"
      username: <input UN>
      password: <input PW>
      transport: cli

  tasks:
    - name: New User Creation
      nxos_user:
        provider: "{{ ssh }}"
        name: ansible
        state: present
        roles: network-admin
        configured_password: ansible
        update_password: on_create
