---
- name: Templating VXLAN Config
  template:
    src: vxlan.j2
    dest: "./config_files/VXLAN_config/{{ inventory_hostname }}.conf"

- name: Pushing VXLAN Config
  nxos_config:
    provider: "{{ nxos_provider }}"
    src: "./config_files/VXLAN_config/{{ inventory_hostname }}.conf"
