---
- name: Building and applying Interface configuration
  template:
    src: intefaces.j2
    dest: ./config_files/{{ inventory hostname }}.conf

#- name: Push NX-OS configs
#  hosts: nxos
#  tasks:
#    - nxos_config:
#        provider: "{{ nxos_provider }}"
#        src: "./config_files/{{ inventory_hostname }}.txt"
