---
- name: Building and applying Interface configuration
  template:
    src: interfaces.j2
    dest: "./config_files/{{ inventory_hostname }}.conf"

- name: Push NX-OS configs
  nxos_config:
    provider: "{{ nxos_provider }}"
    src: "./config_files/{{ inventory_hostname }}.conf"
