---
- name: Templating Interface Config
  template:
    src: base_conf.j2
    dest: "./config_files/Base_config/{{ inventory_hostname }}.conf"

- name: Pushing Interface Config
  nxos_config:
    provider: "{{ nxos_provider }}"
    src: "./config_files/Base_config/{{ inventory_hostname }}.conf"
