---
name: "Leaf-3"
role: "Leaf"

#Transport Mechanism CLI for the moment will change to the API in future
nxos_provider:
  username: "{{ ansible_user }}"
  password: "{{ ansible_password }}"
  transport: cli
  host: "{{ ansible_host }}"

#Interface Section
interfaces:
  ethernet1/3:
    ipv4: "10.0.0.5"
    ipv4_mask: 31
    description: "Link to Spine-1"
    type: "routed"
  ethernet1/4:
    ipv4: "10.0.1.5"
    ipv4_mask: 31
    description: "Link to Spine-2"
    type: "routed"
  loopback0:
    ipv4: "100.127.10.3"
    ipv4_mask: 32
    description: "Router ID"

#BGP Section
asn: 64522
bgp_networks:
  - "100.127.10.3/32"
bgp_neighbor:
  10.0.0.4:
    local_address: "10.0.0.5"
    remote_asn: "64512"
    description: "eBGP to Spine-1"
  10.0.1.4:
    local_address: "10.0.1.5"
    remote_asn: "64513"
    description: "eBGP to Spine-2"

#VXLAN Section
vxlan_role: "Leaf"
vni:
  1001:
    vnid: "1001"
    type: "L2"
    rd: "2012:1001"
    vrf: "Cust-A"
    vlan: 10
    ipv4_gw: "10.10.10.1"
    ipv4_mask: 24
    agw_mac: "0200.0000.1001"
    intf:
      ethernet1/10:
        type: "access"
      ethernet:1/11:
        type: "trunk"

l3_vni:
  3001:
    vnid: "3001"
    vlan: 3001
    vrf: "Cust-A"
    rd: "2012:3001"
