---
name: "Spine-1"
role: "Spine"

#Transport Mechanism CLI for the moment will change to the API in futer
nxos_provider:
  username: "{{ ansible_user }}"
  password: "{{ ansible_password }}"
  transport: cli
  host: "{{ ansible_host }}"

#Interface Section
interfaces:
  ethernet1/1:
    ipv4: "10.0.0.0"
    ipv4_mask: 31
    description: "Link to Leaf-1"
  ethernet1/2:
    ipv4: "10.0.0.2"
    ipv4_mask: 31
    description: "Link to Leaf-2"
  ethernet1/3:
    ipv4: "10.0.0.4"
    ipv4_mask: 31
    description: "Link to Leaf-3"
  ethernet1/4:
    ipv4: "10.0.0.6"
    ipv4_mask: 31
    description: "Link to Leaf-4"
  loopback0:
    ipv4: "100.127.1.1"
    ipv4_mask: 32
    description: "Router ID"

#BGP Section
asn: 64512
bgp_networks:
  - "100.127.1.1/32"
bgp_neighbor:
  10.0.0.1:
    local_address: "10.0.0.0"
    remote_asn: "64520"
    description: "eBGP to Leaf-1"
    bfd: "True"
  10.0.0.3:
    local_address: "10.0.0.2"
    remote_asn: "64521"
    description: "eBGP to Leaf-2"
  10.0.0.5:
    local_address: "10.0.0.4"
    remote_asn: "64522"
    description: "eBGP to Leaf-3"
  10.0.0.7:
    local_address: "10.0.0.6"
    remote_asn: "64523"
    description: "eBGP to Leaf-4"
