---
- name: Templating eBGP Underlay Config
  template:
    src: bgp.j2
    dest: "./config_files/ebgp_underlay_config/{{ inventory_hostname }}.conf"

- name: Pushing eBGP Underlay Config
  nxos_config:
    provider: "{{ nxos_provider }}"
    src: "./config_files/ebgp_underlay_config/{{ inventory_hostname }}.conf"
